version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build:
      context: . 
      dockerfile: dockerfile  
    container_name: waterbus-combine-video
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}" 
    command: ["python", "app.py"]
    env_file:
      - .env 

volumes:
  rabbitmq_data:
